# SPDX-License-Identifier: MIT

feature.safetyStrategy.enabled=true
feature.archiveFlag.default=false
db.field.safety_strategy=safety_strategy
db.field.approve_status=approve_status
label.ja.safetyStrategy=安全方針
label.zh.safetyStrategy=安全策略
